### ISSUE TITLE
pubg_python.exceptions.APIError: Something went wrong with your request

### ISSUE THREAD

**Issue by BoredMind** [Haza/pubg-discord-stats#2]
> Traceback (most recent call last):
>   File "main.py", line 131, in <module>
>     InitMatchesPerUser(api, userList)
>   File "/home/ubuntu/pubg-discord-stats/prefly.py", line 11, in InitMatchesPerUser
>     for player in players:
>   File "/usr/local/lib/python3.5/dist-packages/pubg_python/decorators.py", line 23, in wrapper
>     self.fetch()
>   File "/usr/local/lib/python3.5/dist-packages/pubg_python/querysets.py", line 43, in fetch
>     self._data = self.client.request(self.endpoint)
>   File "/usr/local/lib/python3.5/dist-packages/pubg_python/clients.py", line 30, in request
>     raise exception()
> pubg_python.exceptions.APIError: Something went wrong with your request
> Unclosed client session
> client_session: <aiohttp.client.ClientSession object at 0x7f53d6cfbdd8>

This happens when starting the bot.  I've not change anything in the code or my configs when this started happening.  Any ideas?

**Comment by BoredMind** [comment]
Figured it out.    Had to change `api = PUBG(config['api']['key'], Shard.PC_EU)` to `api = PUBG(config['api']['key'], Shard.PC_NA)` as I'm tracking players in NA
